# Generated by Django 4.0.8 on 2022-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0009_alter_seoultable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObCctvtable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ob_cctvtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObResttable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('food_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ob_resttable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObStreettable',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ob_streettable',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MusinsaTable',
        ),
        migrations.DeleteModel(
            name='ObList',
        ),
        migrations.DeleteModel(
            name='ShopList',
        ),
    ]
